import DataTable from "react-data-table-component";

const columns = [
    {
        name: "No",
        selector: (row) => row.no,
        sortable: true,
    },
    {
        name: "Kode",
        selector: (row) => row.kode,
        sortable: true,
    },
    {
        name: "Kategori",
        selector: (row) => row.kategori,
        sortable: true,
    },
    {
        name: "Nama Sekolah",
        selector: (row) => row.nama_sekolah,
        sortable: true,
    },
    {
        name: "Provinsi",
        selector: (row) => row.provinsi,
        sortable: true,
    },
    {
        name: "Kota",
        selector: (row) => row.kota,
        sortable: true,
    },
    {
        name: "Aksi",
        selector: (row) => row.aksi,
        sortable: true,
    },
];

const data = [
    {
        id: 1,
        no: 1,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 2,
        no: 2,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 3,
        no: 3,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 4,
        no: 4,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 5,
        no: 5,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 6,
        no: 6,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 7,
        no: 7,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 8,
        no: 8,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 9,
        no: 9,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 10,
        no: 10,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 11,
        no: 11,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 12,
        no: 12,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 13,
        no: 13,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 14,
        no: 14,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
    {
        id: 15,
        no: 15,
        kode: 1000,
        kategori: "Negeri",
        nama_sekolah: "SMA Negeri 1 Kota Jakarta",
        provinsi: "DKI Jakarta",
        kota: "Jakarta",
        aksi: "ANJAY",
    },
];

export default function Table() {
    return <DataTable columns={columns} data={data} pagination />;
}
